In [1]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

/home/vishal/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/vishal/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/vishal/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/vishal/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: 

In [2]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [3]:
x_train=x_train.reshape(x_train.shape[0],-1)/255.0
x_test=x_test.reshape(x_test.shape[0],-1)/255.0
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [4]:
print(y_train.shape)
print(y_test.shape)

(60000, 10)
(10000, 10)


In [5]:
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [6]:
model=Sequential()
model.add(Dense(10,input_dim=784,activation='relu'))
model.add(Dense(10,activtion='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


TypeError: ('Keyword argument not understood:', 'activtion')

In [7]:
model=Sequential()
model.add(Dense(10,input_dim=784,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=10, validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/10
54000/54000 [==============================] - 3s 52us/sample - loss: 0.7063 - acc: 0.7488 - val_loss: 0.5186 - val_acc: 0.8107
Epoch 2/10
54000/54000 [==============================] - 2s 42us/sample - loss: 0.4896 - acc: 0.8282 - val_loss: 0.4603 - val_acc: 0.8363
Epoch 3/10
54000/54000 [==============================] - 2s 43us/sample - loss: 0.4494 - acc: 0.8448 - val_loss: 0.4420 - val_acc: 0.8398
Epoch 4/10
54000/54000 [==============================] - 2s 42us/sample - loss: 0.4281 - acc: 0.8498 - val_loss: 0.4260 - val_acc: 0.8503
Epoch 5/10
54000/54000 [==============================] - 2s 42us/sample - loss: 0.4153 - acc: 0.8538 - val_loss: 0.4235 - val_acc: 0.8505
Epoch 6/10
54000/54000 [==============================] - 2s 42us/sample - loss: 0.4055 - acc: 0.8591 - val_loss: 0.4197 - val_acc: 0.8527
Epoch 7/10
54000/54000 [==============================] - 3s 55us/sample - loss: 0.3958 - acc: 0.8599 - val_loss: 0.4

In [9]:
_, test_acc = model.evaluate(x_test, y_test)
print(test_acc)

10000/10000 [==============================] - 0s 23us/sample - loss: 0.4379 - acc: 0.8455
0.8455


In [10]:
model2=Sequential()
model2.add(Dense(50,input_dim=784,activation='relu'))
model2.add(Dense(10,activation='softmax'))
model2.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [11]:
model2.fit(x_train, y_train, epochs=10, validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/10
54000/54000 [==============================] - 3s 53us/sample - loss: 0.5404 - acc: 0.8125 - val_loss: 0.4289 - val_acc: 0.8455
Epoch 2/10
54000/54000 [==============================] - 3s 52us/sample - loss: 0.4107 - acc: 0.8563 - val_loss: 0.4104 - val_acc: 0.8547
Epoch 3/10
54000/54000 [==============================] - 3s 58us/sample - loss: 0.3708 - acc: 0.8692 - val_loss: 0.3925 - val_acc: 0.8615
Epoch 4/10
54000/54000 [==============================] - 3s 51us/sample - loss: 0.3478 - acc: 0.8751 - val_loss: 0.3782 - val_acc: 0.8628
Epoch 5/10
54000/54000 [==============================] - 3s 51us/sample - loss: 0.3299 - acc: 0.8813 - val_loss: 0.3757 - val_acc: 0.8585
Epoch 6/10
54000/54000 [==============================] - 3s 53us/sample - loss: 0.3173 - acc: 0.8853 - val_loss: 0.3455 - val_acc: 0.8793
Epoch 7/10
54000/54000 [==============================] - 3s 53us/sample - loss: 0.3036 - acc: 0.8899 - val_loss: 0.3

In [12]:
_, test_acc = model2.evaluate(x_test, y_test)
print(test_acc)

10000/10000 [==============================] - 0s 26us/sample - loss: 0.3630 - acc: 0.8706
0.8706


In [13]:
model3=Sequential()
model3.add(Dense(50,input_dim=784,activation='relu'))
model3.add(Dense(50,activation='relu'))
model3.add(Dense(10,activation='softmax'))

In [14]:
model3.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [15]:
model3.fit(x_train,y_train,epochs=10,validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/10
54000/54000 [==============================] - 3s 61us/sample - loss: 0.5394 - acc: 0.8110 - val_loss: 0.4207 - val_acc: 0.8487
Epoch 2/10
54000/54000 [==============================] - 3s 55us/sample - loss: 0.3958 - acc: 0.8562 - val_loss: 0.3920 - val_acc: 0.8583
Epoch 3/10
54000/54000 [==============================] - 3s 61us/sample - loss: 0.3568 - acc: 0.8711 - val_loss: 0.3710 - val_acc: 0.8662
Epoch 4/10
54000/54000 [==============================] - 3s 57us/sample - loss: 0.3349 - acc: 0.8780 - val_loss: 0.3407 - val_acc: 0.8750
Epoch 5/10
54000/54000 [==============================] - 3s 61us/sample - loss: 0.3153 - acc: 0.8858 - val_loss: 0.3426 - val_acc: 0.8773
Epoch 6/10
54000/54000 [==============================] - 3s 51us/sample - loss: 0.3026 - acc: 0.8883 - val_loss: 0.3317 - val_acc: 0.8788
Epoch 7/10
54000/54000 [==============================] - 3s 51us/sample - loss: 0.2928 - acc: 0.8924 - val_loss: 0.3

In [16]:
_,test_acc=model3.evaluate(x_test,y_test)
print(test_acc)

10000/10000 [==============================] - 0s 28us/sample - loss: 0.3780 - acc: 0.8736
0.8736


In [17]:
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten
import numpy as np

In [18]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [19]:
print(x_train)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [20]:
print(x_train.shape)

(60000, 28, 28, 1)


In [21]:
model4=Sequential()
model4.add(Conv2D(filters=64,kernel_size=2,padding='same',activation='relu',input_shape=(28,28,1)))
model4.add(MaxPooling2D(pool_size=2))
model4.add(Flatten())
model4.add(Dense(10,activation='softmax'))
model4.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model4.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 64)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 12544)             0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                125450    
Total params: 125,770
Trainable params: 125,770
Non-trainable params: 0
_________________________________________________________________


In [23]:
model4.fit(x_train,y_train,epochs=10,validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/10
54000/54000 [==============================] - 29s 545us/sample - loss: 0.4348 - acc: 0.8485 - val_loss: 0.3290 - val_acc: 0.8802
Epoch 2/10
54000/54000 [==============================] - 32s 588us/sample - loss: 0.3086 - acc: 0.8912 - val_loss: 0.3111 - val_acc: 0.8897
Epoch 3/10
54000/54000 [==============================] - 31s 581us/sample - loss: 0.2773 - acc: 0.9017 - val_loss: 0.2831 - val_acc: 0.9002
Epoch 4/10
54000/54000 [==============================] - 30s 553us/sample - loss: 0.2569 - acc: 0.9089 - val_loss: 0.2910 - val_acc: 0.8947
Epoch 5/10
54000/54000 [==============================] - 29s 540us/sample - loss: 0.2401 - acc: 0.9149 - val_loss: 0.2733 - val_acc: 0.9053
Epoch 6/10
54000/54000 [==============================] - 29s 534us/sample - loss: 0.2270 - acc: 0.9194 - val_loss: 0.2652 - val_acc: 0.9085
Epoch 7/10
54000/54000 [==============================] - 31s 568us/sample - loss: 0.2151 - acc: 0.9223 -

In [24]:
_, test_acc = model4.evaluate(x_test, y_test)
print(test_acc)

10000/10000 [==============================] - 2s 185us/sample - loss: 0.2816 - acc: 0.9004
0.9004
